services:
  postgres:
    image: postgres:15
    container_name: tasks_postgres
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d tasks_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./focus-backend
      dockerfile: Dockerfile
      network: host
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    container_name: tasks_backend
    volumes:
      - ./focus-backend:/app
    ports:
      - "8000:8000"
    environment:
      - CONN_STRING=postgresql://taskuser:taskpass@postgres:5432/tasks_db
    depends_on:
      postgres:
        condition: service_healthy
    command: ["uv","run","uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./daily-tasks-app  
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: tasks_frontend
    volumes:
      - ./daily-tasks-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://0.0.0.0:8000
    depends_on:
      - backend

volumes:
  postgres_data: 