services:
  postgres:
    image: postgres:15
    container_name: tasks_postgres
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d tasks_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Build React app to static files
  frontend-builder:
    build:
      context: ./daily-tasks-app  
      dockerfile: Dockerfile.build
    container_name: tasks_frontend_builder
    volumes:
      - react_build:/app/build
    command: npm run build

  backend:
    build:
      context: ./focus-backend
      dockerfile: Dockerfile
      network: host
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    container_name: tasks_backend
    volumes:
      - ./focus-backend:/app
      - react_build:/app/static  # Mount React build files to backend static directory
    ports:
      - "8000:8000"
    environment:
      - CONN_STRING=postgresql://taskuser:taskpass@postgres:5432/tasks_db
    depends_on:
      postgres:
        condition: service_healthy
      frontend-builder:
        condition: service_completed_successfully
    command: ["uv","run","uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
  react_build:  # Volume to store React build files 