
services:
  postgres:
    image: postgres:15
    container_name: tasks_postgres
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d tasks_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./focus-backend
      dockerfile: Dockerfile
      network: host
    container_name: tasks_backend
    network_mode: host
    volumes:
      - ./focus-backend:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=taskuser
      - DB_PASSWORD=taskpass
      - DB_NAME=tasks_db
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./daily-tasks-app  
      dockerfile: Dockerfile
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: tasks_frontend
    volumes:
      - ./daily-tasks-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://0.0.0.0:8000
    depends_on:
      - backend

volumes:
  postgres_data: 